Repository daveshanley/vacuum, pull requests merged in 2022-10, with the labels that each got.

#134 feat: Docker related improvements
  Dockerfile
  README.md
Labels: release/patch

#136 refactor: change `plugin/sample` package to `sample`
  plugin/sample/boot.go
  plugin/sample/boot_test.go
  plugin/sample/check_single_path.go
  plugin/sample/useless_func.go
Labels: release/patch

#139 Rule updates to address issue #137 and #138
  functions/openapi/operation_descriptions.go
  functions/openapi/operation_descriptions_test.go
  functions/openapi/operation_tags.go
  functions/openapi/operation_tags_test.go
Labels: release/patch

#140 feat(pre-commit): add hook config
  .pre-commit-hooks.yaml
  README.md
Labels: feature

#141 fix(paths): use allowlist instead of blocklist to filter operation checks
  functions/openapi/operation_descriptions.go
  functions/openapi/operation_descriptions_test.go
  functions/openapi/operation_tags.go
  functions/openapi/operation_tags_test.go
Labels: bugfix

#144 Update tag.yaml
  .github/workflows/tag.yaml
Labels: bugfix

#147 feat(pre-commit): improve default matching and docs
  .pre-commit-hooks.yaml
  README.md
Labels: release/patch

#146 fix(lint): clarify error messages to say one filename arg is supported
  cmd/lint.go
Labels: release/patch

#149 feat: add shell argument completions
  cmd/dashboard.go
  cmd/generate_ruleset.go
  cmd/html_report.go
  cmd/lint.go
  cmd/root.go
  cmd/spectral_report.go
  cmd/vacuum_report.go
Labels: release/patch

#151 Fixed `operation_descriptions` function to remedy #148
  functions/openapi/operation_descriptions.go
Labels: release/patch

#150 fix(spectral-report): command name in example
  cmd/spectral_report.go
Labels: release/patch

#156 refactor: use model.SeverityError throughout
  cmd/lint.go
  cmd/lint_test.go
  cmd/shared_functions.go
  functions/core/alphabetical_test.go
  functions/core/casing_test.go
  functions/core/core_test.go
  functions/core/defined_test.go
  functions/core/enumeration_test.go
  functions/core/falsy_test.go
  functions/core/length_test.go
  functions/core/pattern_test.go
  functions/core/truthy_test.go
  functions/core/undefined_test.go
  functions/core/xor_test.go
  html-report/build_report.go
  model/results.go
  model/results_test.go
  model/rules.go
  model/rules_test.go
  motor/rule_applicator.go
  motor/rule_applicator_test.go
  rulesets/ruleset_functions.go
  rulesets/rulesets.go
  rulesets/rulesets_test.go
  vacuum-report/vacuum_report_test.go
Labels: cleanup

#152 Add vacuum executable to PATH
  Dockerfile
Labels: enhancement

#158 Added support for swagger security requirements #154
  functions/openapi/unused_component.go
  functions/openapi/unused_component_test.go
  go.mod
  go.sum
Labels: dependencies, bugfix

#159 Release v0.0.35
  .github/workflows/tag.yaml
Labels: release/patch

#164 (fix): Bugfix for issue #163
  functions/core/truthy.go
  functions/core/truthy_test.go
Labels: release/patch, bugfix
